### ISSUE TITLE
led-panel-single: verified the design works well

### ISSUE THREAD

**Issue by TomKeddie** [icebreaker-fpga/icebreaker-pmod#11]
This is not an issue as such.  I've built a version of led-panel-single with a more hand solderable part selection.  The files are at https://github.com/TomKeddie/icebreaker-pmod/tree/tomk_20230129_ledpanel/led-panel-single/v1.0a  - the schematic is the same.  I'm using it to drive panels just fine.  I wont be merging it anywhere as it's purely derivative of the design that's here.

The shape is a little peculiar.

![2023-03-30-07-37-10-803](https://user-images.githubusercontent.com/4367175/228873033-e2b382a7-15ec-4d1d-b1ca-f4044fba5c89.jpg)

**Comment by esden** [comment]
If you want, we could merge it into the main repo here too. The more the merrier. I like the look of the board. :)
